name: CI/CD for ToDoListAPI

on:
  push:
    branches:
      - CI/CD2
  pull_request:
    branches:
      - CI/CD2

jobs:
  build-test-push-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for ToDoListAPI
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todolistapi:latest .  # Убрали -f, так как файл называется Dockerfile

      - name: Create Docker network and run containers
        run: |
          docker network create todo_network || true
          docker run -d --name todo_mssql --network todo_network -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=L1234qwer%" -e "MSSQL_PID=Express" mcr.microsoft.com/mssql/server:2019-latest
          docker run -d --name todo_api --network todo_network -p 8090:8090 ${{ secrets.DOCKERHUB_USERNAME }}/todolistapi:latest

      - name: Wait for containers to be ready
        run: |
          sleep 30

      - name: Test API health
        run: |
          curl --retry 5 --retry-delay 5 --retry-max-time 30 http://localhost:8090/api/tasks || exit 1
          echo "API is up and running!"

      - name: Stop and clean up containers
        if: always()
        run: |
          docker stop todo_mssql todo_api || true
          docker rm todo_mssql todo_api || true
          docker network rm todo_network || true

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todolistapi:latest